### ISSUE TITLE
Version 2.21.1 exhibits breaking imports in SvelteKit project.

### ISSUE THREAD

**Issue by jamesb93** [freesewing/freesewing#2342]
**What seems to be the problem?**

Since the update of `remark-jargon` to `2.21.1` my SvelteKit project breaks on build. I get this error message I try to run my build script:

```
> require() of ES Module /Users/james/dev/flucoma/learn/node_modules/.pnpm/unist-util-visit@4.1.0/node_modules/unist-util-visit/index.js from /Users/james/dev/flucoma/learn/node_modules/.pnpm/remark-jargon@2.21.1_axyox3zfhduo4zma2odzxqzoxa/node_modules/remark-jargon/dist/index.js not supported.
Instead change the require of /Users/james/dev/flucoma/learn/node_modules/.pnpm/unist-util-visit@4.1.0/node_modules/unist-util-visit/index.js in /Users/james/dev/flucoma/learn/node_modules/.pnpm/remark-jargon@2.21.1_axyox3zfhduo4zma2odzxqzoxa/node_modules/remark-jargon/dist/index.js to a dynamic import() which is available in all CommonJS modules.
Instead change the require of /Users/james/dev/flucoma/learn/node_modules/.pnpm/unist-util-visit@4.1.0/node_modules/unist-util-visit/index.js in /Users/james/dev/flucoma/learn/node_modules/.pnpm/remark-jargon@2.21.1_axyox3zfhduo4zma2odzxqzoxa/node_modules/remark-jargon/dist/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/james/dev/flucoma/learn/node_modules/.pnpm/remark-jargon@2.21.1_axyox3zfhduo4zma2odzxqzoxa/node_modules/remark-jargon/dist/index.js:7:469)
    at async Promise.all (index 0)
    at async load_config (file:///Users/james/dev/flucoma/learn/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.321_svelte@3.48.0/node_modules/@sveltejs/kit/dist/cli.js:785:17)
    at async file:///Users/james/dev/flucoma/learn/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.321_svelte@3.48.0/node_modules/@sveltejs/kit/dist/cli.js:924:19
```

Rolling back to `2.20.8` fixes the issue.

**Are you a FreeSewing patron?**

 - [ ] Yes, I am :hugs:
 - [x] No, I am not :thinking:

**Additional context**

Add any other context or screenshots about the problem request here.

I am using SvelteKit version `321`.

**Comment by jamesb93** [comment]
> Whoops, seems like we upgraded to an ESM-only dependency.
> 
> Try the `latest` which is `2.21.2` and it should be ok. If not, re-open.

Wow, thanks for the speedy response time :) I'll check this out today and if you don't hear from me then assume it remained fixed.
