### ISSUE TITLE
[bug]: `npx lerna bootstrap` results in `TypeError: Cannot read properties of undefined (reading 'split')`

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3052]
### What seems to be the problem? 🤔

The `npx lerna bootstrap` operation (which gets run during `yarn kickstart`) is failing with a `TypeError: Cannot read properties of undefined (reading 'split')` message.

```sh
% yarn kickstart
yarn run v1.22.19
$ npx lerna bootstrap && yarn buildall && yarn prepare && yarn tips
lerna notice cli v6.0.1
lerna notice filter excluding "component-*"
lerna info filter [ '!component-*' ]
lerna ERR! TypeError: Cannot read properties of undefined (reading 'split')
lerna ERR!     at Minimatch.match (.../freesewing/node_modules/minimatch/minimatch.js:743:9)
lerna ERR!     at .../freesewing/node_modules/minimatch/minimatch.js:717:15
lerna ERR!     at Array.filter (<anonymous>)
lerna ERR!     at Function.minimatch.match (.../freesewing/node_modules/minimatch/minimatch.js:716:15)
lerna ERR!     at module.exports (.../freesewing/node_modules/multimatch/index.js:25:39)
lerna ERR!     at filterPackages (.../freesewing/node_modules/@lerna/filter-packages/filter-packages.js:44:28)
lerna ERR! lerna Cannot read properties of undefined (reading 'split')
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is with the `develop` branch.

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

For the purposes of `yarn kickstart`, I was able to workaround the issue by skipping the `npx lerna bootstrap` operation and manually running `yarn buildall`, `yarn prepare`, and `yarn tips` manually. The subsequent `yarn lab` operation seemed to still work fine without the lerna bootstrap.

**Comment by BenJamesBen** [comment]
I don't fully understand the issue or its cause. However, I note that the following change to `sites/email/package.json` seems to fix the issue:
```diff
--- a/sites/email/package.json
+++ b/sites/email/package.json
@@ -1,4 +1,5 @@
 {
+  "name": "testing",
   "private": true,
   "scripts": {
     "dev": "maizzle serve",
```

The lerna filter operation was coming across something that was `undefined` when processing `sites/*`. It appears that the new `sites/email/package.json` was missing the `name` field, and that is what was `undefined`.
