### ISSUE TITLE
[bug]: Enable/Disable debug in Hugo breaks v2 patterns

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#3340]
### What seems to be the problem? 🤔

Jan from Germany writes (via email):

> When I open my pattern "Hugo for J", activate the expert mode, activate debug, and again deactivate debug, I get the following error messages and no pattern anymore:
```js
TypeError: Cannot read properties of undefined (reading 'debug')
    at Q.attr (https://freesewing.org/1ffd4cd39d205f07bf8e65eb702fdf17140cdb39-1643285425ebebae5429.js:2:38289)
    at po.draftPocket (https://freesewing.org/31bab55aefe452cf658c07b729c343551f861ba3-a7f544d9c39281701ae3.js:2:403604)
    at qt.draft (https://freesewing.org/1ffd4cd39d205f07bf8e65eb702fdf17140cdb39-1643285425ebebae5429.js:2:77095)
    at ve (https://freesewing.org/d93a31d262fce01b759cdcef25fe3d83549681eb-c3635e8675141ca3922b.js:2:74612)
    at fe (https://freesewing.org/d93a31d262fce01b759cdcef25fe3d83549681eb-c3635e8675141ca3922b.js:2:75224)
    at oo (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:59972)
    at $o (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:69490)
    at Ku (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:113027)
    at Li (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:99326)
    at Ni (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:99254)

TypeError: Cannot read properties of undefined (reading 'line')
    at po.draftPocketFacing (https://freesewing.org/31bab55aefe452cf658c07b729c343551f861ba3-a7f544d9c39281701ae3.js:2:404908)
    at qt.draft (https://freesewing.org/1ffd4cd39d205f07bf8e65eb702fdf17140cdb39-1643285425ebebae5429.js:2:77095)
    at ve (https://freesewing.org/d93a31d262fce01b759cdcef25fe3d83549681eb-c3635e8675141ca3922b.js:2:74612)
    at fe (https://freesewing.org/d93a31d262fce01b759cdcef25fe3d83549681eb-c3635e8675141ca3922b.js:2:75224)
    at oo (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:59972)
    at $o (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:69490)
    at Ku (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:113027)
    at Li (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:99326)
    at Ni (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:99254)
    at Pi (https://freesewing.org/framework-a6c6740318fe12224bf3.js:2:99117)
  ```

### Are you a FreeSewing patron? 😃

Yes, I am a tier-2 patron ❤️

### Additional context

Not sure we'll get around to fixing this v2 issue since debug has been dropped in v3

**Comment by BenJamesBen** [comment]
The same sort of error occurs with a few other patterns on `freesewing.org`, including Carlton and Charlie.

The error message I see with Hugo is:
```Error: Unable to draft part pocket
TypeError: undefined is not an object (evaluating 'this.raise.debug')
```

I notice that in all the affected designs when `debug` is enabled, a debug message is logged saying that `Path.attribute.class` was overwritten. Because of this, I suspect the error might be occurring in `Path.prototype.attr()`:
```js
  if (overwrite)
    this.raise.debug(
      `Overwriting \`Path.attribute.${name}\` with ${value} (was: ${this.attributes.get(name)})`
    )
```

**Comment by BenJamesBen** [comment]
Closing as Fixed in v3 to indicate that the bug is still present in v2 but is not present in v3. (The bug wasn't actually "fixed". It is just that there is no more `debug` in v3, so the bug isn't seen.)
