### ISSUE TITLE
[bug]: (new-design) Dev environment missing Mermaid support and unable to run

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#3844]
### What seems to be the problem? 🤔

`npx @freesewing/new-design@next` standalone environment installs are unable to run due to missing Mermaid support.
```sh
% yarn dev
...
error - ./shared/components/mdx/highlight.mjs:3:0
Module not found: Can't resolve './mermaid.mjs'
  1 | import { CopyToClipboard } from 'shared/components/copy-to-clipboard.mjs'
  2 | import { HttpStatusCode } from './http.mjs'
> 3 | import { Mermaid } from './mermaid.mjs'
  4 | 
  5 | const names = {
  6 |   js: 'Javascript',
```

### Design / Plugin / Package 🧐

packages/new-design

### Are you a FreeSewing patron? 😃

No, I am not 😞

### Additional context

A workaround is to:
1. copy the file at `https://raw.githubusercontent.com/freesewing/freesewing/develop/sites/shared/components/mdx/mermaid.mjs` to `shared/components/mdx/mermaid.mjs` and 
2. `yarn add mermaid` in the created folder

**Comment by marpants** [comment]
I believe the bug will be resolved with the changes in #3845 , however I see a new problem now which I haven't yet found a root cause for:
```
tutorial$ yarn dev
yarn run v1.22.19
$ next dev -p 8000
ready - started server on 0.0.0.0:8000, url: http://localhost:8000
warn  - Invalid next.config.mjs options detected: 
warn  -     The value at .i18n has an unexpected property, defaultNS, which is not in the list of allowed properties (defaultLocale, domains, localeDetection, locales).
warn  - See more info here: https://nextjs.org/docs/messages/invalid-next-config

🌼 daisyUI components 2.51.5  https://daisyui.com
  ✔︎ Including:  base, components, 4 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
  
event - compiled client and server successfully in 3.7s (218 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 1364 ms (389 modules)
error - Error: Default namespace not found at public/locales/en/common.json
    at createConfig (/home/marpants/freesewing/packages/new-design/tutorial/node_modules/next-i18next/dist/commonjs/config/createConfig.js:165:19)
    at _callee$ (/home/marpants/freesewing/packages/new-design/tutorial/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:201:53)
    at tryCatch (/home/marpants/freesewing/packages/new-design/tutorial/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/home/marpants/freesewing/packages/new-design/tutorial/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/home/marpants/freesewing/packages/new-design/tutorial/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/home/marpants/freesewing/packages/new-design/tutorial/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/marpants/freesewing/packages/new-design/tutorial/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9) {
  digest: undefined
}
```

**Comment by marpants** [comment]
OK I think the above is related to how I'm running the package locally.. I think I'd need some help testing properly 😅

**Comment by joostdecock** [comment]
> I believe the bug will be resolved with the changes in #3845 , however I see a new problem now which I haven't yet found a root cause for:
> 
> ```
> error - Error: Default namespace not found at public/locales/en/common.json
> ```


You need to run `yarn prebuild` in the `sites/dev` folder prior to running `yarn dev` as the prebuild step will generate the language files.
For further updates to language files, could can run `yarn i18n` which is faster, but only prebuilds the language files (the prebuild step does more than that)

**Comment by BenJamesBen** [comment]
I'm still seeing the errors after a fresh `npx @freesewing/new-design@next` install, and the files don't seem to be there either. Is there an additional deploy step that hasn't yet been done to get the updated files into the `new-design` package?

**Comment by marpants** [comment]
My understanding from @joostdecock (please correct if I'm wrong) is that while the package is pulling content from the dev branch (which is why we see the updates changes to highlight.msj) the list of files to pull and how it composed the package.json are part of the next-design package itself, so that won't change until the npm package is updated... Still trying to better understand the deployment pipelines... But yes, I think we will need support from @joostdecock or someone else to help with that part.

**Comment by joostdecock** [comment]
@marpants you are correct :)
I'll start working on putting out a new release so this is addressed

**Comment by BenJamesBen** [comment]
I tested it and verified that the bug is fixed.
