### ISSUE TITLE
CFP is broken due to breaking changes in execa

### ISSUE THREAD

**Issue by joostdecock** [freesewing/freesewing#491]
create-freesewing-pattern is broken in 2.8.0 because:

```
× Running npm install and npm link
TypeError: execa.shell is not a function
at C:\Users\DocSpencer\AppData\Roaming\npm-cache_npx\3292\node_modules\create-freesewing-pattern\lib\create-library.js:111:18
at pEachSeries (C:\Users\DocSpencer\AppData\Roaming\npm-cache_npx\3292\node_modules\create-freesewing-pattern\node_modules\p-each-series\index.js:8:9)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

We've updated to execa 4, but it seemed we (as in, I) didn't bother to check for breaking changes.

**Comment by joostdecock** [comment]
Fixed in https://github.com/freesewing/freesewing/commit/8964b183496e8bfc6991df5e49e722079ab61692
