### ISSUE TITLE
[bug]: New design environment doesn't work

### ISSUE THREAD

**Issue by HaasJona** [freesewing/freesewing#6430]
### What seems to be the problem? 🤔

I'm having issues using the new design dev environment. This worked a few weeks ago, but now I'm getting errors:

```
jh@fedora:~/WebstormProjects$ npx @freesewing/new-design

   ___            ___             _
  | __| _ ___ ___/ __| _____ __ _(_)_ _  __ _
  | _| '_/ -_) -_)__ \/ -_) V  V / | ' \/ _` |
  |_||_| \___\___|___/\___|\_/\_/|_|_||_\__, |
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡|___/
  Come for the sewing patterns
  Stay for the community

✔ Give a folder name in which we can setup the development environment? 🏷️  … test
✔ What package manager should we use? 📦 › yarn

✔ 🟩⬜⬜  Downloaded 720/720 files from GitHub
✖ 🟩🟥⬜  Failed to install dependencies  |  The development environment will not function
✔ 🟩🟩🟩  Initialized git repository

  All done 🤓 Your FreeSewing development environment was initialized in: /var/home/jh/WebstormProjects/test

  The templates for various designs are in the design folder.
  The other files and folders are the development environment. You can safely ignore those.

  To start your development environment, follow these three steps:

    1) Start by entering the directory: cd /var/home/jh/WebstormProjects/test
    2) Then run this command: yarn dev
    3) Now open your browser and navigate to http://localhost:8000/

  Thanks for giving FreeSewing a shot. I hope you'll 💜 it.

  Have fun 🤓

  joost

jh@fedora:~/WebstormProjects$ cd test/
jh@fedora:~/WebstormProjects/test$ yarn dev
Internal Error: @freesewing/sde@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Xx.getCandidates (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:205:8149)
    at Dd.getCandidates (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:141:1311)
    at /var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:210:8409
    at Ky (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:140:53916)
    at Fe (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:210:8389)
    at async Promise.allSettled (index 0)
    at async Uc (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:140:53244)
    at async /var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:210:9140
    at async Qi.startProgressPromise (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:140:137284)
    at async Pt.resolveEverything (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:210:7138)
jh@fedora:~/WebstormProjects/test$ yarn install
➤ YN0000: · Yarn 4.1.0
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: svg-to-pdfkit@https://git@github.com/eriese/SVG-to-PDFKit: Manifest not found
    at AE.find (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:140:120021)
    at async /var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:559:12938
    at async Object.bZe (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:140:53847)
    at async G2.resolve (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:559:12899)
    at async Dd.resolve (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:141:1451)
    at async Dd.resolve (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:141:1451)
    at async /var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:210:7249
    at async Ky (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:140:53910)
    at async ne (/var/home/jh/.volta/tools/image/yarn/4.1.0/bin/yarn.js:210:7231)
    at async Promise.allSettled (index 54)
➤ YN0000: └ Completed in 0s 316ms
➤ YN0000: · Failed with errors in 0s 327ms
```

Is there some dependency update needed?

### Design / Plugin / Package 🧐

packages/new-design

**Comment by joostdecock** [comment]
Tx for reporting this in detail @HaasJona 
I'll have a look at this tomorrow.

**Comment by joostdecock** [comment]
I cannot reproduce this. Is it possible you are using a non-default branch?

Try:
```
env | grep FS_BRANCH
```

**Comment by HaasJona** [comment]
I don't think so.

```
jh@fedora:~/WebstormProjects$ env | grep FS_BRANCH
jh@fedora:~/WebstormProjects$ npx @freesewing/new-design

   ___            ___             _
  | __| _ ___ ___/ __| _____ __ _(_)_ _  __ _
  | _| '_/ -_) -_)__ \/ -_) V  V / | ' \/ _` |
  |_||_| \___\___|___/\___|\_/\_/|_|_||_\__, |
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡|___/
  Come for the sewing patterns
  Stay for the community

✔ Give a folder name in which we can setup the development environment? 🏷️  … ttt
✔ What package manager should we use? 📦 › yarn

✔ 🟩⬜⬜  Downloaded 720/720 files from GitHub
✖ 🟩🟥⬜  Failed to install dependencies  |  The development environment will not function
✔ 🟩🟩🟩  Initialized git repository

  All done 🤓 Your FreeSewing development environment was initialized in: /var/home/jh/WebstormProjects/ttt

  The templates for various designs are in the design folder.
  The other files and folders are the development environment. You can safely ignore those.

  To start your development environment, follow these three steps:

    1) Start by entering the directory: cd /var/home/jh/WebstormProjects/ttt
    2) Then run this command: yarn dev
    3) Now open your browser and navigate to http://localhost:8000/

  Thanks for giving FreeSewing a shot. I hope you'll 💜 it.

  Have fun 🤓

  joost

jh@fedora:~/WebstormProjects$ yarn -v
4.1.0
jh@fedora:~/WebstormProjects$ node -v
v20.11.1
```

**Comment by HaasJona** [comment]
Error happens regardless if I choose yarn or npm. However with npm, the installation spams lots of debug calls like this:

```
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Function: handleRequestSocket]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/freesewing/freesewing/v3.1.0/sites/shared/components/workbench/views/cut/menu.mjs',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'raw.githubusercontent.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/freesewing/freesewing/v3.1.0/sites/shared/components/workbench/views/cut/menu.mjs'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /freesewing/freesewing/v3.1.0/sites/shared/components/workbench/views/cut/menu.mjs HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.6.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: raw.githubusercontent.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/freesewing/freesewing/v3.1.0/sites/shared/components/workbench/views/cut/menu.mjs',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'raw.githubusercontent.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://raw.githubusercontent.com/freesewing/freesewing/v3.1.0/sites/shared/components/workbench/views/cut/menu.mjs',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```

Maybe that helps.

I can access https://raw.githubusercontent.com/freesewing/freesewing/v3.1.0/sites/shared/components/workbench/views/cut/menu.mjs in the browser no problem.

**Comment by joostdecock** [comment]
That `connectiinReset` error is GitHub rate limiting.

Could you could run it again (same folder name) and pick the **download** option? That will re-download the files, which should fix any gaps due to the rate limiting being triggered

**Comment by HaasJona** [comment]
That fixed the downloading files with npm issue, but the `svg-to-pdfkit@https://git@github.com/eriese/SVG-to-PDFKit: Manifest not found` error stays the same.

**Comment by BenJamesBen** [comment]
I am not able to reproduce the issue. I tested `npx @freesewing/new-design` using both Node `lts/hydrogen` and `lts/iron`, using both `npm` and `yarn`.

Regarding `yarn`, I note that I used version 1.22.21 installed via `npm`, not the modern version.

**Comment by HaasJona** [comment]
Weird, might be an issue with my computer, will do some further testing.

**Comment by joostdecock** [comment]
Might be worth to try running the v1 yarn @HaasJona
Yarn v1 is the _production_ version: https://www.npmjs.com/package/yarn?activeTab=versions

I presume you perhaps installed if via yum manager, and that's how you ended up with v4?

```
jh@fedora:~/WebstormProjects$ yarn -v
4.1.0
```

Might be a good idea to try:
```
npm i -g yarn
```

Although that should not play a role when using npm so 🤷

**Comment by HaasJona** [comment]
Can't reproduce this anymore, so closing this. There was clearly something borked on my system.
