### ISSUE TITLE
[bug]: The `rehype-jargon` plugin seems unable to handle nested elements inside `em` elements gracefully

### ISSUE THREAD

**Issue by jlvandenhout** [freesewing/freesewing#6471]
### What seems to be the problem? 🤔

The `rehype-jargon` plugin seems unable to handle nested elements inside `em` elements gracefully. For example, our website has an element like this: `<em><strong>Deprecated</strong></em>`. The following line then tries to get the value of the `em` element, which isn't there I guess, because there is a nested `strong` 
 element: https://github.com/freesewing/freesewing/blob/cd5b4b58b6c5e07bd8a563d1a428501f019f6456/packages/rehype-jargon/src/index.mjs#L20 

This results in the following error:

```
Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
Error: MDX compilation failed for file "/home/develop/repositories/iota-wiki/docs/build/identity.rs/1.1/docs/references/api/wasm.md"
Cause: Cannot read properties of undefined (reading 'toLowerCase')
Details:
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at e (/home/develop/repositories/iota-wiki/node_modules/rehype-jargon/dist/index.mjs:12:334)
    at n (/home/develop/repositories/iota-wiki/node_modules/rehype-jargon/dist/index.mjs:12:372)
    at overload (/home/develop/repositories/iota-wiki/node_modules/unist-util-visit/lib/index.js:475:155)
    at node (element<em>) (/home/develop/repositories/iota-wiki/node_modules/unist-util-visit-parents/lib/index.js:471:27)
    at node (element<p>) (/home/develop/repositories/iota-wiki/node_modules/unist-util-visit-parents/lib/index.js:471:496)
    at node (root) (/home/develop/repositories/iota-wiki/node_modules/unist-util-visit-parents/lib/index.js:471:496)
    at visitParents (/home/develop/repositories/iota-wiki/node_modules/unist-util-visit-parents/lib/index.js:464:121)
    at visit (/home/develop/repositories/iota-wiki/node_modules/unist-util-visit/lib/index.js:472:96)
    at /home/develop/repositories/iota-wiki/node_modules/rehype-jargon/dist/index.mjs:12:584
    at wrapped (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:160:27)
    at next (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:86:23)
    at done (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:194:7)
    at then (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:204:5)
    at wrapped (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:181:9)
    at next (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:86:23)
    at done (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:194:7)
    at then (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:204:5)
    at wrapped (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:181:9)
    at next (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:86:23)
    at done (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:194:7)
    at then (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:204:5)
    at wrapped (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:181:9)
    at next (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:86:23)
    at done (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:194:7)
    at then (file:///home/develop/repositories/iota-wiki/node_modules/trough/lib/index.js:204:5)
    at Object.mdxLoader (/home/develop/repositories/iota-wiki/node_modules/@docusaurus/mdx-loader/lib/loader.js:130:25)
```

### Design / Plugin / Package 🧐

packages/rehype-jargon

**Comment by jlvandenhout** [comment]
I'm happy to open a PR to resolve this, but I guess there is a choice to be made: either disregard `em` elements that contain nested elements or traverse down to the text node, regardless of nested elements.

**Comment by joostdecock** [comment]
Thanks for reporting this @jlvandenhout 

> *I guess there is a choice to be made: either disregard em elements that contain nested elements or traverse down to the text node, regardless of nested elements.*

I am leaning towards the conservative approach to ignore `em` tags that contain nested elements.
If you really wanted to bold a term, you could always inverse the tag order:

```
<strong><em>Deprecated</em></strong>
```
If you're up for submitting a PR to implement that, it would be much appreciated :pray:

**Comment by jlvandenhout** [comment]
Sure! I'll give it a shot.

**Comment by jlvandenhout** [comment]
I opened a PR here #6778
